[package]
name = "jired"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
keyring = { version = "3.6.2", features = ["linux-native-sync-persistent","linux-native","sync-secret-service"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
